### PR TITLE
Bug 1972903: Add missing return statement

### LINKED ISSUE #1126: DirectVolumeMigration goes to next step even though namespace isn't created
**Describe the bug**
This is created to fix a bug when attempting staging step from source to destination. It was observed that the during CreateDestinationPVCs step , the logs reported namespaces "example" not found.

Release version : 1.4.4

**Proposed Fix**
Adding return err when an error occurs creating the namespace : https://github.com/konveyor/mig-controller/blob/release-1.4.4/pkg/controller/directvolumemigration/task.go#L232

### PR DESCRIPTION
**Pull request by pranavgaikwad**
Fixes #1126

### CODE REVIEW

File: pkg/controller/directvolumemigration/task.go [hunk 1]
```diff
@@ -222,7 +222,7 @@ func (t *Task) Run(ctx context.Context) error {
 		// destination
 		err := t.ensureDestinationNamespaces()
 		if err != nil {
-			liberr.Wrap(err)
+			return liberr.Wrap(err)
```
Comment (alaypatel07) [inline pkg/controller/directvolumemigration/task.go:225]: will this not fail when the namespace already exists?

Comment (pranavgaikwad) [reply pkg/controller/directvolumemigration/task.go:225]: @alaypatel07 right, I missed that. adding an error check in the function

Comment (pranavgaikwad) [reply pkg/controller/directvolumemigration/task.go:225]: @alaypatel07 added the check

**Comment by pranavgaikwad** [comment]
GH Action failure is a known issue today. It should be fixed once GH resolves the Ubuntu archive issue. I ran `make test` on my machine and didn't see any failures.

File: pkg/controller/directvolumemigration/task.go (hunk 1 above)
Comment (alaypatel07) [reply pkg/controller/directvolumemigration/task.go:225]: @pranavgaikwad +1, I think there is another check to be made here, i.e. if namespace.finalizer is set. If that is set the namespace is in delete mode i.e. it will be deleted soon when the itinerary is in the next steps

**Review by alaypatel07 — APPROVED** [review]
VISIACK
