### PR TITLE
Fix DVM/DVMP hotlooping, remove remote watch TouchAnnotation, fix requeues so they used values from r.Migrate()

### LINKED ISSUE #1011: DVM, DVMP (possibly DIM, DISM) sometimes hotloop
**Describe the bug**
I discovered that the controllers added in release-1.4.0 are relying on TouchAnnotation for requeues in some places, which is causing excessive reconciles in DVMP / DVM. I don't believe the function or existence of TouchAnnotation was known when writing the controllers.

After removing TouchAnnotation (a relic of remote watch that should not be used without predicates, which are also not present) the controllers get stuck in various places and do not complete the migration. 

Solution is two things:
 - Remove TouchAnnotation to eliminate echo reconciles
 - Respect RequeueAfter times returned from `r.migrate()`

We need to fix these issues so that DVM and DVMP won't hotloop waiting for Pods to progress.

### PR DESCRIPTION
**Pull request by djwhatle**
Closes #1011

### CODE REVIEW

File: pkg/apis/migration/v1alpha1/directvolumemigrationprogress_types.go [hunk 1]
```diff
@@ -64,11 +63,9 @@ type DirectVolumeMigrationProgress struct {
 }
 
 func (d *DirectVolumeMigrationProgress) MarkReconciled() {
-	u, _ := uuid.NewUUID()
 	if d.Annotations == nil {
 		d.Annotations = map[string]string{}
 	}
-	d.Annotations[TouchAnnotation] = u.String()
```
Comment (djwhatle) [inline pkg/apis/migration/v1alpha1/directvolumemigrationprogress_types.go:71]: This TouchAnnotation is an unintended leftover from the remote watch system. This was likely causing requeues where they shouldn't have been happening in DVM/DVMP.

File: pkg/controller/directimagemigration/directimagemigration_controller.go [hunk 2]
```diff
@@ -117,17 +118,20 @@ func (r *ReconcileDirectImageMigration) Reconcile(request reconcile.Request) (re
 		if errors.IsNotFound(err) {
 			// Object not found, return.  Created objects are automatically garbage collected.
 			// For additional cleanup logic use finalizers.
-			return reconcile.Result{}, nil
+			return reconcile.Result{Requeue: false}, nil
```
Comment (djwhatle) [inline pkg/controller/directimagemigration/directimagemigration_controller.go:121]: I think it's more obvious what's happening if we explicitly use the requeue flag

File: pkg/controller/directimagemigration/directimagemigration_controller.go [hunk 3]
```diff
@@ -117,17 +118,20 @@ func (r *ReconcileDirectImageMigration) Reconcile(request reconcile.Request) (re
...
 	}
 
 	// Completed.
 	if imageMigration.Status.Phase == Completed {
-		return reconcile.Result{}, nil
+		return reconcile.Result{Requeue: false}, nil
 	}
 
+	// Default re-queue (after) in seconds.
+	requeueAfter := time.Duration(PollReQ)
```
Comment (djwhatle) [inline pkg/controller/directimagemigration/directimagemigration_controller.go:133]: PollReQ is the default, and it is overridden by the output of `r.migrate` below. This is the combination that has been proven to work well, tested heavily during removal of remote watch. 

After removing the TouchAnnotation (which causes constant echo reconciles), I saw migrations halt in the middle because they weren't using the output of r.Migrate in DIM, DISM, DVM, DVMP.

File: pkg/controller/directimagemigration/directimagemigration_controller.go [hunk 4]
```diff
@@ -139,7 +143,7 @@ func (r *ReconcileDirectImageMigration) Reconcile(request reconcile.Request) (re
 	}
 
 	if !imageMigration.Status.HasBlockerCondition() {
-		_, err = r.migrate(imageMigration)
+		requeueAfter, err = r.migrate(imageMigration)
```
Comment (djwhatle) [inline pkg/controller/directimagemigration/directimagemigration_controller.go:146]: No longer throwing away the requeueAfter, so now if a requeue duration is sleected in phase logic it actually gets used.

File: pkg/apis/migration/v1alpha1/directvolumemigrationprogress_types.go (hunk 1 above)
Comment (alaypatel07) [reply pkg/apis/migration/v1alpha1/directvolumemigrationprogress_types.go:71]: +1000, thanks for removing this

File: pkg/controller/directimagemigration/directimagemigration_controller.go (hunk 3 above)
Comment (alaypatel07) [reply pkg/controller/directimagemigration/directimagemigration_controller.go:133]: +1. thanks for digging into this, makes a lot of sense

Comment (alaypatel07) [reply pkg/controller/directimagemigration/directimagemigration_controller.go:133]: for locality, do you think moving this to just before the if block at line 145 makes sense? would make the code much more readable when coming back to this in the future.

File: pkg/controller/directvolumemigrationprogress/directvolumemigrationprogress_controller.go [hunk 5]
```diff
@@ -171,7 +171,7 @@ func (r *ReconcileDirectVolumeMigrationProgress) Reconcile(request reconcile.Req
 	}
 
 	if !pvProgress.Status.IsReady() {
-		return reconcile.Result{Requeue: true}, nil
+		return reconcile.Result{Requeue: true, RequeueAfter: time.Second * 5}, nil
```
Comment (alaypatel07) [inline pkg/controller/directvolumemigrationprogress/directvolumemigrationprogress_controller.go:174]: I wonder if this if block is necessary? looks like the intent is to requeue at 5 seconds irrespective of the status

**Review by alaypatel07 — APPROVED** [review]
Just small re-org comments and minor nit on if block otherwise looks good to me

VISIACK

File: pkg/controller/directvolumemigrationprogress/directvolumemigrationprogress_controller.go (hunk 5 above)
Comment (djwhatle) [reply pkg/controller/directvolumemigrationprogress/directvolumemigrationprogress_controller.go:174]: Yeah maybe not, let me take a look and see if it's safe to remove

File: pkg/controller/directimagemigration/directimagemigration_controller.go (hunk 3 above)
Comment (djwhatle) [reply pkg/controller/directimagemigration/directimagemigration_controller.go:133]: Yeah I think that makes sense, will change 👍

File: pkg/controller/directvolumemigration/task.go [hunk 6]
```diff
@@ -512,7 +512,6 @@ func (t *Task) Run() error {
 
 	if t.Phase == Completed {
 		t.Requeue = NoReQ
-		t.Log.Info("[COMPLETED]")
```
Comment (djwhatle) [inline pkg/controller/directvolumemigration/task.go:515]: No idea why this got removed, I am adding it back

**Comment by djwhatle** [comment]
I verified there is no observable perf change from this PR, which is what I expected. The goal of this PR is to reduce pointless API requests without reducing our migration performance.

### Migration time for rocket-chat (this PR):
2 minutes, 55 seconds

### Migration time for rocket-chat (master)
2 minutes, 56 seconds

**Review by alaypatel07 — APPROVED** [review]
thanks for the changes, added a small nit, feel free to merge after that from my end.

VISIACK

**Review by sseago — APPROVED** [review]

File: pkg/controller/directimagestreammigration/directimagestreammigration_controller.go [hunk 7]
```diff
@@ -154,6 +158,10 @@ func (r *ReconcileDirectImageStreamMigration) Reconcile(request reconcile.Reques
...
 	}
 
-	// Done
-	return reconcile.Result{}, nil
+	// Requeue
+	if requeueAfter > 0 {
+		return reconcile.Result{RequeueAfter: requeueAfter}, nil
+	}
+
+	return reconcile.Result{Requeue: false}, nil
```
[the remark this answers is not in the document]
Comment (djwhatle) [reply pkg/controller/directimagestreammigration/directimagestreammigration_controller.go:166]: Good point, will update.
